# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python application

on:
  push:
    branches: 
      - '*' 
  pull_request:
    branches: 
      - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      run: |
        black .
    - name: Test with unittest
      run: |
        python -m unittest discover tests
